#!/usr/bin/env python3
"""Day-0 MachineConfig for a shared ostree /var/lib/containers partition.

Uploaded to Assisted Installer in the ``openshift`` folder so Ignition can
carve the slice at first boot (root must not already fill the disk).
"""
from __future__ import annotations

import yaml

import env_config

MANIFEST_FILE = "98-containers-part.yaml"
MACHINECONFIG_NAME = "98-var-lib-containers-partitioned"
# Backup GPT + alignment at end of disk. start+size must not equal disk size
# (300GiB = 100GiB root + 200GiB containers filled every sector and hung Ignition).
GPT_TAIL_MIB = 1024


def is_enabled() -> bool:
    return env_config.containers_partition_gb() > 0


def start_mib() -> int:
    return env_config.containers_partition_start_gb() * 1024


def size_mib() -> int:
    """Containers partition size: spec GiB minus 1GiB so GPT backup fits."""
    raw = env_config.containers_partition_gb() * 1024
    if raw <= GPT_TAIL_MIB:
        raise SystemExit(
            f"containers_partition.gb is too small to leave {GPT_TAIL_MIB}MiB for GPT"
        )
    return raw - GPT_TAIL_MIB


def machineconfig_yaml(
    *,
    device: str,
    start_mib: int,
    size_mib: int,
) -> str:
    """RHCOS extra partition MC (IBI shared containers stateroot)."""
    body = {
        "apiVersion": "machineconfiguration.openshift.io/v1",
        "kind": "MachineConfig",
        "metadata": {
            "labels": {"machineconfiguration.openshift.io/role": "master"},
            "name": MACHINECONFIG_NAME,
        },
        "spec": {
            "config": {
                "ignition": {"version": "3.2.0"},
                "storage": {
                    "disks": [
                        {
                            "device": device,
                            "partitions": [
                                {
                                    "label": "var-lib-containers",
                                    "startMiB": start_mib,
                                    "sizeMiB": size_mib,
                                }
                            ],
                        }
                    ],
                    "filesystems": [
                        {
                            "device": "/dev/disk/by-partlabel/var-lib-containers",
                            "format": "xfs",
                            "mountOptions": ["defaults", "prjquota"],
                            "path": "/var/lib/containers",
                            "wipeFilesystem": True,
                        }
                    ],
                },
                "systemd": {
                    "units": [
                        {
                            "contents": (
                                "# Generated by dsx-air\n"
                                "[Unit]\n"
                                "Before=local-fs.target\n"
                                "Requires=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2dcontainers.service\n"
                                "After=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2dcontainers.service\n"
                                "\n"
                                "[Mount]\n"
                                "Where=/var/lib/containers\n"
                                "What=/dev/disk/by-partlabel/var-lib-containers\n"
                                "Type=xfs\n"
                                "Options=defaults,prjquota\n"
                                "\n"
                                "[Install]\n"
                                "RequiredBy=local-fs.target\n"
                            ),
                            "enabled": True,
                            "name": "var-lib-containers.mount",
                        }
                    ]
                },
            }
        },
    }
    return yaml.safe_dump(body, sort_keys=False)


def assisted_openshift_manifests() -> list[dict[str, str]]:
    """ailib ``openshift_manifests`` entries, or empty when disabled."""
    if not is_enabled():
        return []
    if len(MANIFEST_FILE) > 30:
        raise SystemExit(f"Assisted extra-manifest filename too long: {MANIFEST_FILE}")
    text = machineconfig_yaml(
        device=env_config.containers_partition_device(),
        start_mib=start_mib(),
        size_mib=size_mib(),
    )
    return [{MANIFEST_FILE: text}]
